# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TT8iLy292QpVdEdQ0gtWElPKGcP9znp3
"""

def mostrar_menu():
    print("\n--- 🍔 MENÚ DEL RESTAURANTE ---")
    print("1. Ver menú")
    print("2. Calcular total")
    print("3. Cambiar nombre del cliente")
    print("4. Salir")
    print("5. Calcular precio con IVA")

def ejecutar_asistente():
    cliente = "Invitado"
    continuar = True

    while continuar:
        mostrar_menu()
        opcion = input("Seleccione una opción (1-5): ")

        if opcion == "1":
            print("🍕 Pizza: $2000\n🍔 Hamburguesa: $1500")
        elif opcion == "2":
            total = int(input("Ingrese el total sin IVA: "))
            print(f"💰 Total: ${total}")
        elif opcion == "3":
            cliente = input("Ingrese su nombre: ")
            print(f"👤 Bienvenido {cliente}")
        elif opcion == "4":
            print(f"👋 Gracias por venir, {cliente}")
            continuar = False
        elif opcion == "5":
            precio = int(input("Ingrese precio: "))
            total = precio * 1.21
            print(f"💸 Precio con IVA: ${total}")
        else:
            print("❌ Opción inválida")

ejecutar_asistente()